services:
  user.api:
    image: ${DOCKER_REGISTRY-}userapi
    build:
      context: .
      dockerfile: User.API/Dockerfile

  yarpgateway.api:
    image: ${DOCKER_REGISTRY-}yarpgatewayapi
    build:
      context: .
      dockerfile: YARPGateway.API/Dockerfile

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq

  mongodb:
    image: mongo:latest
    container_name: mongodb


  logmessagebroker.api:
    image: ${DOCKER_REGISTRY-}logmessagebrokerapi
    build:
      context: .
      dockerfile: LogMessageBroker.API/Dockerfile

