apiVersion: v1
kind: Service
metadata:
  name: user-api-service
spec:
  selector:
    app: user-api
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
    - port: 8081
      targetPort: 8081
      protocol: TCP
      name: https
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: yarpgateway-api-service
spec:
  selector:
    app: yarpgateway-api
  ports:
    - port: 8084
      targetPort: 8084
      protocol: TCP
      name: http
    - port: 8085
      targetPort: 8085
      protocol: TCP
      name: https
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: logmessagebroker-api-service
spec:
  selector:
    app: logmessagebroker-api
  ports:
    - port: 5060
      targetPort: 5060
      protocol: TCP
      name: http
    - port: 5061
      targetPort: 5061
      protocol: TCP
      name: https
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service
spec:
  selector:
    app: rabbitmq
  ports:
    - port: 5672
      targetPort: 5672
      protocol: TCP
      name: amqp
    - port: 15672
      targetPort: 15672
      protocol: TCP
      name: management
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
spec:
  selector:
    app: mongodb
  ports:
    - port: 27017
      targetPort: 27017
      protocol: TCP
      name: mongodb
  type: ClusterIP
