---
apiVersion: v1
kind: Service
metadata:
  name: user-api-service
spec:
  selector:
    app: user-api
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30000
      protocol: TCP
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: yarpgateway-api-service
spec:
  selector:
    app: yarpgateway-api
  ports:
    - port: 8084
      targetPort: 8084
      nodePort: 30001
      protocol: TCP
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: logmessagebroker-api-service
spec:
  selector:
    app: logmessagebroker-api
  ports:
    - port: 5060
      targetPort: 5060
      nodePort: 30002
      protocol: TCP
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service
spec:
  selector:
    app: rabbitmq
  ports:
    - port: 5672
      targetPort: 5672
      nodePort: 30003
      protocol: TCP
      name: amqp
    - port: 15672
      targetPort: 15672
      nodePort: 30004
      protocol: TCP
      name: management
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
spec:
  selector:
    app: mongodb
  ports:
    - port: 27017
      targetPort: 27017
      nodePort: 30005
      protocol: TCP
  type: NodePort
